### ISSUE TITLE
P1: Add a "Host Tips" page

### ISSUE THREAD

**Issue by heathermleroy** [rylero/jobshadow#12]
We do not need a top level menu item for this page.  It is just something we need to refer to from multiple places.
jobcamp.org/host-tips

It will be referred to from the FAQs page and I would like to put it somewhere in the Company Sign Up flow - that will be a separate issue I'll log once I can view the site.

**Comment by rylero** [comment]
Duplicate issue. Refer to issue #16.

**Comment by dleroy** [comment]
Closed as duplicate
