### ISSUE TITLE
I am able to create a job position for a date that doesn't align with the event date

### ISSUE THREAD

**Issue by dleroy** [rylero/jobshadow#28]
When I created my first position, it allowed me to create a position date that doesn't align with the event date. See image below

<img width="838" alt="Screenshot 2023-11-15 at 2 51 24 PM" src="https://github.com/rylero/jobshadow/assets/547827/e2b2a43d-5c0e-46f1-b793-5379d1965e2d">

**Comment by rylero** [comment]
Copy of #26
