### ISSUE TITLE
Company Information is not editable

### ISSUE THREAD

**Issue by dleroy** [rylero/jobshadow#31]
When a new company registers, they enter details about the company like Name, description, logo,etc..   Once that company is registered they can not go back and edit or add any of these details. 
It seems company info + positions should be displayed on the company dashboard.

<img width="795" alt="Screenshot 2023-11-16 at 8 45 43 AM" src="https://github.com/rylero/jobshadow/assets/547827/d6941bab-6868-46b9-b286-0b214ff63986">

**Comment by heathermleroy** [comment]
The P1 here is to make the company information visible underneath the "Your Events" box. 
Title should read "Your Company Info" in a box similar to the "Your Events" info.
Add a pencil icon to allow the user to edit the Company Info by popping a separate form.
Note:  editing the logo is a maybe.
