### ISSUE TITLE
404 error when trying to go to company dashboard

### ISSUE THREAD

**Issue by dleroy** [rylero/jobshadow#5]
I signed up for a new company account. I got the email to verify, clicked the link, and then closed that window. I went back to the original tab that says 'go to your dashboard'. I clicked the linked 'dashboard' and it went here:
![bug](https://github.com/rylero/jobshadow/assets/547827/6d744193-5a40-43ef-8a90-e3451ca859ef)

**Comment by rylero** [comment]
Migrated to firebase hosting which resolved error.
