### ISSUE TITLE
Replace template about page template with actual verbage

### ISSUE THREAD

**Issue by dleroy** [rylero/jobshadow#8]
Get verbiage from Heather

Current text {
    "mainText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Magna sit amet purus gravida quis blandit turpis cursus in. Sem viverra aliquet eget sit amet. Auctor eu augue ut lectus arcu bibendum. Eu turpis egestas pretium aenean pharetra magna. Scelerisque in dictum non consectetur. Faucibus ornare suspendisse sed nisi lacus. Urna condimentum mattis pellentesque id nibh. Nam libero justo laoreet sit amet cursus sit. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Feugiat nisl pretium fusce id velit ut. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Morbi blandit cursus risus at ultrices mi. Eu sem integer vitae justo eget. Elementum integer enim neque volutpat. Sed turpis tincidunt id aliquet risus feugiat. Lacus laoreet non curabitur gravida. Nec ultrices dui sapien eget." 
}

**Comment by rylero** [comment]
Replaced content
